# Generated by Django 5.2.17 on 2026-09-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('policy_mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IntruderAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('sniper', 'Sniper'), ('batteringRam', 'Battering Ram'), ('pitchfork', 'Pitchfork'), ('clusterBomb', 'Cluster Bomb')], max_length=20)),
                ('base_request', models.JSONField()),
                ('payloads', models.JSONField()),
                ('transformations', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('safe', 'Safe Mode'), ('authorized', 'Authorized Testing Mode')], default='safe', max_length=20)),
                ('allowed_hosts', models.JSONField(default=list)),
                ('authorized_targets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('url', models.URLField(max_length=2048)),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_headers', models.JSONField(default=dict)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
