# Generated by Django 5.2.17 on 2026-09-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_trafficrecord_proxy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='intruderattack',
            name='name',
            field=models.CharField(default='Intruder attack', max_length=120),
        ),
    ]
