# Generated by Django 5.2.17 on 2026-09-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_intruderattack_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Traffic session', max_length=160)),
                ('items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
