# Generated by Django 5.2.17 on 2026-09-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_trafficsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficrecord',
            name='source',
            field=models.CharField(choices=[('repeater', 'Repeater'), ('intruder', 'Intruder'), ('proxy', 'Proxy')], default='repeater', max_length=20),
        ),
    ]
