# Generated by Django 5.2.17 on 2026-09-18 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_intruderattack_delay_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('plan', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('tool', models.CharField(max_length=80)),
                ('arguments', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lab.agentrun')),
            ],
            options={
                'ordering': ['ordinal', 'id'],
                'unique_together': {('run', 'ordinal')},
            },
        ),
    ]
