# Generated by Django 5.2.17 on 2026-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0015_agentevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="intruderattack",
            name="concurrency",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
