# Generated by Django 5.2.17 on 2026-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0016_intruderattack_concurrency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intruderattack",
            name="delay_ms",
            field=models.PositiveIntegerField(default=150),
        ),
    ]
